-- Tạo bảng FileDinhKemEmail
CREATE TABLE FileDinhKemEmail (
    KeyID_SendEmail UNIQUEIDENTIFIER NULL,
    DuongDan NVARCHAR(MAX) NULL
);

-- Tạo bảng MailMage
CREATE TABLE MailMage (
    KeyID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Status NVARCHAR(255) NULL,
    DateCreate DATETIME DEFAULT GETDATE(),
    NguoiTao NVARCHAR(100) NULL,
    DuongDanHTMLMau NVARCHAR(500) NULL,
    DuongDanKetQua NVARCHAR(500) NULL,
    AAA01 NVARCHAR(255) NULL,
    AAA02 NVARCHAR(255) NULL,
    AAA03 NVARCHAR(255) NULL,
    AAA04 NVARCHAR(255) NULL,
    AAA05 NVARCHAR(255) NULL,
    AAA06 NVARCHAR(255) NULL,
    AAA07 NVARCHAR(255) NULL,
    AAA08 NVARCHAR(255) NULL,
    AAA09 NVARCHAR(255) NULL,
    AAA10 NVARCHAR(255) NULL,
    AAA11 NVARCHAR(255) NULL,
    AAA12 NVARCHAR(255) NULL,
    AAA13 NVARCHAR(255) NULL,
    AAA14 NVARCHAR(255) NULL,
    AAA15 NVARCHAR(255) NULL,
    AAA16 NVARCHAR(255) NULL,
    AAA17 NVARCHAR(255) NULL,
    AAA18 NVARCHAR(255) NULL,
    AAA19 NVARCHAR(255) NULL,
    AAA20 NVARCHAR(255) NULL
);

-- Tạo bảng SendEmail
CREATE TABLE SendEmail (
    KeyID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    NgayTao DATETIME DEFAULT GETDATE(),
    NguoiTao NVARCHAR(100) NULL,
    EmailGui NVARCHAR(255) NULL,
    EmailAPI NVARCHAR(255) NULL,
    TieuDeEmail NVARCHAR(255) NULL,
    EmailNhan NVARCHAR(255) NULL,
    EmailNhanCC NVARCHAR(255) NULL,
    EmailNhanBCC NVARCHAR(255) NULL,
    NoiDungHTML NVARCHAR(MAX) NULL,
    TrangThai NVARCHAR(255) NULL
);
